import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# Simulated email folder inside backend
LOGS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "email_logs")

def trigger_deadzone_alert(provider, report_count, lat, lng, sample_coords):
    """
    Triggers an email alert to telecom support.
    If SMTP env variables are not set, it simulates sending by saving a local log file.
    """
    os.makedirs(LOGS_DIR, exist_ok=True)
    
    # SMTP Configuration (Fallback to local simulation if not specified)
    smtp_server = os.getenv("SMTP_SERVER", "")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_password = os.getenv("SMTP_PASSWORD", "")
    support_email = os.getenv("TELECOM_SUPPORT_EMAIL", "support@telecom.com")
    from_email = os.getenv("SENDER_EMAIL", "alerts@deadzonelocator.org")

    # Construct email details
    subject = f"[ALERT] Potential {provider} Dead Zone Proximity Identified"
    
    body = f"""
========================================================================
HYPERLOCAL DEAD ZONE ALERT SYSTEM - AUTOMATIC INCIDENT REPORT
========================================================================
Timestamp: {datetime.utcnow().isoformat()}Z
Mobile Operator: {provider}
Incident Classification: POTENTIAL DEAD ZONE
Trigger Radius: 200 Meters
Proximity Threshold: 3+ reports within a 30-minute window
------------------------------------------------------------------------

SUPPORT TEAM INCIDENT SUMMARY:
We have detected a cluster of {report_count} mobile network reports in close proximity 
indicating a potential network coverage gap.

Approximate Proximity Center:
- Latitude: {lat:.6f}
- Longitude: {lng:.6f}
- Google Maps URL: https://www.google.com/maps?q={lat:.6f},{lng:.6f}

Report Cluster Coordinates:
{chr(10).join([f"  • {c[0]:.6f}, {c[1]:.6f} (Time: {c[2]})" for c in sample_coords])}

Suggested Action:
We recommend dispatching a field engineer or performing network parameter 
optimizations for towers serving this proximity sector.

========================================================================
This is an automated alert generated by Hyperlocal Dead Zone Locator system.
"""

    print(f"\n[ALERT SYSTEM] Potential dead zone detected for {provider}! Compiling incident summary...")

    # If SMTP settings are provided, attempt to send
    if smtp_server and smtp_user and smtp_password:
        try:
            msg = MIMEMultipart()
            msg["From"] = from_email
            msg["To"] = support_email
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "plain"))

            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(smtp_user, smtp_password)
                server.sendmail(from_email, support_email, msg.as_string())
            print(f"[ALERT SYSTEM] Email alert successfully sent to {support_email} via SMTP.")
        except Exception as e:
            print(f"[ALERT SYSTEM] ERROR: Failed to send SMTP email: {e}")
            simulate_alert_delivery(subject, body, provider)
    else:
        # Simulate local alert file delivery
        simulate_alert_delivery(subject, body, provider)

def simulate_alert_delivery(subject, body, provider):
    """
    Saves the email alert content into a text log file in the backend directory.
    """
    timestamp_str = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    file_name = f"alert_{provider}_{timestamp_str}.txt"
    file_path = os.path.join(LOGS_DIR, file_name)
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(f"Subject: {subject}\n\n{body}")
        
    print(f"[ALERT SYSTEM] [SIMULATION] Saved incident summary to:\n -> {file_path}")
